
version: '3'

services:

  pgsql:
    build: .
    container_name: pgsql-dev
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - ${DOCKER_HOME}/pgsql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
