
version: '2'

services:

  mysql:
    build: .
    image: mysql/mac
    container_name: mysql-run
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ~/Docker/mysql:/var/lib/mysql
    ports:
      - 3309:3306

  mongo:
    image: mongo:3.4
    container_name: mongo-run
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="root"
      - MONGODB_PASS="123456"
    volumes:
      - ~/Docker/mongo/db:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:4.0
    container_name: redis-run
    volumes:
      - ~/Docker/redis/data:/data
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
