
version: '2'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ~/Docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  mongo:
    image: mongo:3.4
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="root"
      - MONGODB_PASS="123456"
    volumes:
      - ~/Docker/mongo/db:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:4.0
    container_name: redis
    volumes:
      - ~/Docker/redis/data:/data
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]

  registry:
    image: registry:2
    container_name: registry
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    restart: always
    volumes:
      - ~/Docker/docker-hub/registry:/var/lib/registry
      - ~/Docker/docker-hub/certs:/certs
      - ~/Docker/docker-hub/config.yml:/etc/docker/registry/config.yml
    ports:
      - 5000:5000
