
version: '2'

services:

  mysql:
    extends:
      file: docker-compose.yml
      service: mysql
    build:
      dockerfile: Dockerfile_m1
    platform: linux/arm64/v8

  mongo:
    extends:
      file: docker-compose.yml
      service: mongo

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  zookeeper:
    extends:
      file: docker-compose.yml
      service: zookeeper

  kafka:
    extends:
      file: kafka/docker-compose.yml
      service: kafka
    platform: linux/arm64
    container_name: kafka-dev
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-dev:2181

  es:
    extends:
      file: docker-compose.yml
      service: es
    platform: linux/arm64
    build:
      dockerfile: Dockerfile_m1

  hbase:
    extends:
      file: docker-compose.yml
      service: hbase

  clash:
    extends:
      file: docker-compose.yml
      service: clash
