
version: '2'

services:

  mysql:
    extends:
      file: docker-compose.yml
      service: mysql
    platform: linux/amd64

  mongo:
    extends:
      file: docker-compose.yml
      service: mongo

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  zookeeper:
    extends:
      file: docker-compose.yml
      service: zookeeper

  kafka:
    extends:
      file: docker-compose.yml
      service: kafka
    platform: linux/amd64

  es:
    extends:
      file: docker-compose.yml
      service: es
    platform: linux/arm64
    build:
      dockerfile: Dockerfile_m1

  hbase:
    extends:
      file: docker-compose.yml
      service: hbase

  clash:
    extends:
      file: docker-compose.yml
      service: clash
