
version: '2'

services:

  mysql:
    extends:
      file: docker-compose.yml
      service: mysql
    build:
      dockerfile: Dockerfile_m1
    platform: linux/arm64/v8

  es:
    extends:
      file: docker-compose.yml
      service: es
    platform: linux/arm64
    build:
      dockerfile: Dockerfile_m1

  pgsql:
    extends:
      file: docker-compose.yml
      service: pgsql
    platform: linux/arm/v6
