
version: '2'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ${DOCKER_HOME}/Docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  mongo:
    image: mongo:3.4
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="root"
      - MONGODB_PASS="123456"
    volumes:
      - ${DOCKER_HOME}/Docker/mongo/db:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:4.0
    container_name: redis
    volumes:
      - ${DOCKER_HOME}/Docker/redis/data:/data
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]

  elasticsearch:
    image: elasticsearch:5-alpine
    container_name: es
    volumes:
      - ${DOCKER_HOME}/Docker/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9300:9300
      - 9200:9200

