
version: '2'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ${DOCKER_HOME}/mysql/data:/var/lib/mysql
      - ${DOCKER_HOME}/mysql/etc:/etc/mysql
    ports:
      - 3306:3306

  mongo:
    image: mongo:3.4
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="root"
      - MONGODB_PASS="123456"
    volumes:
      - ${DOCKER_HOME}/mongo/db:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:4.0
    container_name: redis
    volumes:
      - ${DOCKER_HOME}/redis/data:/data
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    mem_limit: 1024M
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    mem_limit: 1024M
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_NO: 1
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms16M"
    ports:
      - 9092:9092

  elasticsearch:
    build: ./elasticsearch
    image: es:5-mac
    container_name: es
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ${DOCKER_HOME}/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9300:9300
      - 9200:9200

  hbase:
    build: ./hbase
    image: hbase:1.4-mac
    container_name: hbase
    hostname: hbase.local
    volumes:
      - ${DOCKER_HOME}/hbase/data:/data
    ports:
      - 8080:8080
      - 9090:9090
      - 16000:16000
      - 16010:16010
      - 16201:16201
      - 16301:16301
