
version: '2'

services:

  clash:
    build: .
    container_name: clash
    restart: unless-stopped
    volumes:
      - ~/Docker/clash/config:/root/.config/clash
    ports:
      - 8890:7890
      - 8891:7891
