
version: '2'

services:

  clash:
    build: .
    container_name: clash
    restart: unless-stopped
    environment:
      - CONFIG_URL=http://xxx.com/config.yml
    volumes:
      - ~/Docker/clash/config:/root/config
    ports:
      - 8890:7890
      - 8891:7891
