
port: 7890
socks-port: 7891

allow-lan: true
external-controller: 0.0.0.0:8899
mode: Rule
log-level: info

Proxy:
  - {name: 上海1, server: server1, port: 32902, type: ss, cipher: chacha20-ietf, password: xxx}
  - {name: 香港2, server: server2, port: 32902, type: ss, cipher: chacha20-ietf, password: xxx}

Proxy Group:
  - name: 指定节点
    type: select
    proxies:
      - 自动
      - 直连
      - 上海1
      - 香港2
  - name: 自动
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 上海1
      - 香港2
  - name: 直连
    type: select
    proxies:
      - DIRECT
  - name: 拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: FINAL
    type: select
    proxies:
      - 自动
      - 指定节点
      - 直连
      - 拦截

Rule:
  - DOMAIN-SUFFIX,google.com,自动
  - DOMAIN-KEYWORD,google,自动
  - DOMAIN,google.com,自动
  - DOMAIN-SUFFIX,ad.com,拦截
  - IP-CIDR,100.64.0.0/10,直连,no-resolve
  - GEOIP,CN,直连
  - MATCH,FINAL
