version: '3'

services:

  emby-server:
    image: lovechen/embyserver
    container_name: emby_server
    environment:
      - TZ=Asia/Shanghai
      - UID=0
      - GID=0
      - GIDLIST=0
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /share/Container/emby/config:/config
      - /share/Container/emby/data:/data
      - /share/TV:/shares/tv:ro
      - /share/Movie:/shares/movie:ro
      - /share/Music:/shares/music:ro
      - /share/User/CloudDrive:/shares/clouddrive:ro
    ports:
      - 8097:8096
      - 8921:8920
      - 7360:7359/udp
