version: '2'
services:
  docker-registry:
    build: .
    image: docker-registry:2-mac
    container_name: docker-registry
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - ${DOCKER_HOME}/docker-registry/lib:/var/lib/registry
    ports:
      - 5000:5000

