
version: '2'

name: dev

services:

  mongo:
    build: .
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ~/Docker/mongo/db:/data/db
    ports:
      - 27017:27017

  mongo_win:
    build: .
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - D:/Docker/mongo/db:/data/db
    ports:
      - 27017:27017
