
version: '2'

services:

  mongo:
    build: .
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="root"
      - MONGODB_PASS="123456"
    volumes:
      - ${DOCKER_HOME}/mongo/db:/data/db
    ports:
      - 27017:27017
