
version: '2'

services:

  clash:
    build: .
    image: es:5-dms
    container_name: es
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ${DOCKER_HOME}/Docker/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9300:9300
      - 9200:9200
