version: '2'

services:

  es:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: es
    volumes:
      - ~/Docker/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms64m -Xmx256m
    ports:
      - 9300:9300
      - 9200:9200

  es_arm64:
    extends:
      service: es
    build:
      dockerfile: Dockerfile_m1
    platform: linux/arm64
