version: '3'

services:

  xteve:
    image: tnwhitwell/xteve
    container_name: xteve
    restart: unless-stopped
    ports:
      - 34400:34400
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /share/Container/xteve/conf:/config
      - /share/Container/xteve/root:/root/.xteve
      - /share/Container/xteve/tmp:/tmp/xteve
