
FROM jenkins/agent:latest

USER root
ENV TZ=Asia/Shanghai
WORKDIR /home/jenkins/agent

RUN set -eux; \
    sed -i "s/deb.debian.org/mirrors.aliyun.com/g" /etc/apt/sources.list; \
    echo "Asia/Shanghai" > /etc/timezone; \
    curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - ; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
      git \
      nodejs \
    ; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

CMD java -jar /usr/share/jenkins/agent.jar
