version: '3'

services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    volumes:
      - ~/Docker/jenkins/home:/var/jenkins_home
    ports:
      - 8081:8080

  agent:
    build:
      context: .
      dockerfile: Dockerfile_agent
    image: jenkins-agent
    container_name: jenkins-agent
    stdin_open: true
    command: java -jar /usr/share/jenkins/agent.jar -jnlpUrl ${JNLP_URL} -secret ${SECRET}

  docker-api:
    image: alpine/socat
    container_name: jenkins-docker-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2375:2375
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
