version: '2'
services:
  runner:
    build: .
    container_name: actions-runner
    restart: always
    environment:
      REPO: https://github.com/tvrcgo/pika-boilerplate
      TOKEN: <token-from-github>
