version: '2'

name: dev

services:

  mysql:
    build: .
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ~/Docker/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306

  mysql_arm64:
    extends:
      service: mysql
    build:
      dockerfile: Dockerfile_m1
    platform: linux/arm64/v8

  mysql_win:
    extends:
      service: mysql
    volumes:
      - D:/Docker/mysql/data:/var/lib/mysql

  nas:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /share/Container/mysql/data:/var/lib/mysql
      - /share/Container/mysql/etc:/etc/mysql/conf.d
    ports:
      - 3306:3306
