version: 3
name: ai
services:
  ollama_win:
    container_name: ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - D:/Docker/ollama:/root/.ollama
    environment:
      OLLAMA_ORIGINS: "*"
      OLLAMA_HOST: "0.0.0.0"
