
version: '2'

name: dev

services:

  redis:
    build: .
    container_name: redis
    volumes:
      - ~/Docker/redis/data:/data
    ports:
      - 6379:6379

  redis_win:
    build: .
    container_name: redis
    environment:
      - REDIS_PASSWORD=5Rv4fV5G3pv4eU2WHEQg
    volumes:
      - D:/Docker/redis/data:/data
    ports:
      - 6379:6379

  nas:
    image: redis:alpine
    container_name: redis
    volumes:
      - /share/Container/redis/data:/data
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --loglevel warning
