name: Build clash image

on:
  push:
    paths:
      - 'clash/**'
      - '!clash/**/*.md'
      - '.github/workflows/build-clash.yml'
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Push to docker.io
        uses: tvrcgo/docker-builder@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: tvrcgo/clash:latest
          context: ./clash

      - name: Push to aliyun
        uses: tvrcgo/docker-builder@master
        with:
          username: ${{ secrets.ALIYUN_USER }}
          password: ${{ secrets.ALIYUN_PASS }}
          tags: registry.cn-shenzhen.aliyuncs.com/tvrcgo/clash:latest
          registry: registry.cn-shenzhen.aliyuncs.com
          context: ./clash
