name: Push clash image

on:
  push:
    paths:
      - 'clash/**'
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Build and push image
        run: |
          echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin docker.io
          docker build -t docker.io/${DOCKER_REPO}:latest clash/
          docker push docker.io/${DOCKER_REPO}:latest
